# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [5]:
# Import here.
!pip3 install pandas numpy

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [6]:
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

In [ ]:
# Load the Food choices data set into a variable (e.g., df_food).

food_data_set_path = '../data/food_coded.csv' #go up one folder bc hw file is in exercises folder

df_food = pd.read_csv(food_data_set_path)

df_food

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

### Explore the Data

How much data did you just load?

In [8]:
# Count by hand. (lol kidding)

print(df_food.shape) #125 rows x 61 columns

(125, 61)

What are the columns and their types in this data set?

In [9]:
# Show the column names and their types.

df_food.info() #use .info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    str
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    str
 8   comfort_food_reasons          123 non-null    str
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    str
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    str
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    str
 25  fav_cuisine                   123 non-null    str
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    str
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    str
 35  ideal_diet                    124 non-null    str
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    str
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    str
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     str
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    str
dtypes: float64(20), int64(27), str(14)
memory usage: 59.7 KB

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns?

In [10]:
# Remove ‘em.
df_food2 = df_food[['calories_day','weight','Gender']] #create another dataframe with the specified columns only

df_food2

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

What about `NaN`s? How many are there?

In [11]:
# Count ‘em.

count = df_food2.isnull().sum().sum() #counts the number of NaNs in the entire dataframe, for all rows and col
print(count)

21

In [12]:
column_nan_count = df_food2.isnull().sum() #counts the number of NaNs in each column 

print(column_nan_count)

calories_day    19
weight           2
Gender           0
dtype: int64

We gotta remove those `NaN`s―the entire row.

In [13]:
# Drop ‘em.

df_food_drop = df_food2.dropna() #remove any row with NaN (remove the entire row), save in a NEW df variable

In [14]:
df_food_drop

     calories_day                    weight  Gender
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
5             3.0                       190       1
..            ...                       ...     ...
118           3.0                       140       1
119           3.0                       185       2
120           4.0                       156       1
121           2.0                       180       1
123           4.0                       135       2

[104 rows x 3 columns]

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [15]:
df_food_drop.info() #weight datatype is a str

<class 'pandas.DataFrame'>
Index: 104 entries, 1 to 123
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   calories_day  104 non-null    float64
 1   weight        104 non-null    str
 2   Gender        104 non-null    int64
dtypes: float64(1), int64(1), str(1)
memory usage: 3.2 KB

In [16]:
# Fix that.

#Original issue, could not convert the str weight data to int because there was text with the nums
#Line below removes the entire row if has text, but want to keep it
#df_food_w = df_food_drop[df_food_drop['weight'].str.isnumeric()].copy() #store in new df, only extract the numeric values and filter out text

df_food_w = df_food_drop.copy() #create a copy of the df
df_food_w['weight'] = df_food_w['weight'].str.extract(r'(\d+)') #alter the weight col directly to extract the numeric digits, keep the row
#above line keeps all data displayed

df_food_w
# df_food_w2 = df_food_w['weight'].str.extract(r'(\d+)') #Issue: only shows extracted data, only extract the numeric digits, keep the row

# df_food_w2 #df contains the digits only 

#df_food_drop['weight'] = pd.to_numeric(df_food_drop['weight']) - did not work

     calories_day weight  Gender
1             3.0    155       1
2             4.0    NaN       1
3             3.0    240       1
4             2.0    190       1
5             3.0    190       1
..            ...    ...     ...
118           3.0    140       1
119           3.0    185       2
120           4.0    156       1
121           2.0    180       1
123           4.0    135       2

[104 rows x 3 columns]

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [17]:
# Savey save!

df_food_w2 = df_food_w.dropna() #drop the NaN values (after extract)

df_food_w2 #df contains the cleaned data

     calories_day weight  Gender
1             3.0    155       1
3             3.0    240       1
4             2.0    190       1
5             3.0    190       1
6             3.0    180       2
..            ...    ...     ...
118           3.0    140       1
119           3.0    185       2
120           4.0    156       1
121           2.0    180       1
123           4.0    135       2

[103 rows x 3 columns]

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

In [18]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set into a variable (e.g., df_salary).

In [19]:
# 1. Replace this with your actual Google Sheet ID
spreadsheet_id = "1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw"

# 2. Construct the direct TSV export URL
salary_tsv = f"https://docs.google.com/spreadsheets/d/{spreadsheet_id}/export?format=tsv"

# 3. Read the TSV data into a Pandas DataFrame using the tab separator
df_salary = pd.read_csv(salary_tsv, sep='\t')

In [20]:
df_salary

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28221,6/2/2026 14:06:08,25-34,"Accounting, Banking & Finance",Accountant,NaN,53000,6000.0,GBP,NaN,NaN,UK,NaN,London,2 - 4 years,2 - 4 years,College degree,Other or prefer not to answer,Another option not listed here or prefer not t...
28222,6/22/2026 1:24:59,18-24,Education (Higher Education),student,NaN,0,NaN,Other,PKR,NaN,pakistan,NaN,faisalabad,1 year or less,1 year or less,College degree,Man,Another option not listed here or prefer not t...
28223,7/25/2026 5:10:49,18-24,Education (Primary/Secondary),English Teacher,NaN,31200,NaN,Other,MYR,NaN,Malaysia,NaN,Pahang,1 year or less,1 year or less,College degree,Woman,Asian or Asian American
28224,7/27/2026 11:44:14,35-44,Retail,purchasing coordinator,NaN,12000,0.0,USD,NaN,NaN,romania,NaN,bucharest,11 - 20 years,5-7 years,College degree,Man,White
28225,9/17/2026 20:18:08,25-34,Computing or Tech,Arbol,NaN,21,NaN,USD,NaN,NaN,Ecuador,Alabama,Texas,41 years or more,11 - 20 years,High School,Non-binary,Black or African American

Was that hard? 🙃

#### rename the file to something that is better for all systems.  
* No spaces in filename (can use '_')
* all lower case

### Explore

You know the drill.

How much data did you just load?

In [21]:
# Count by hand. I’m dead serious.

print(df_salary.shape) #28226 rows x 18 col

(28226, 18)

What are the columns and their types?

In [22]:
# Show the column names and their types.

df_salary.info() #use .info()

<class 'pandas.DataFrame'>
RangeIndex: 28226 entries, 0 to 28225
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   Timestamp                                                                                                                                                                                                                             28226 non-null  str
 1   How old are you?                                                                                                                                                                                                                      28226 non-null  str
 2   What industry do you work in?                                                                                                                                                                                                         28140 non-null  str
 3   Job title                                                                                                                                                                                                                             28221 non-null  str
 4   If your job title needs additional context, please clarify here:                                                                                                                                                                      7293 non-null   str
 5   What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  28226 non-null  str
 6   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                        20850 non-null  float64
 7   Please indicate the currency                                                                                                                                                                                                          28226 non-null  str
 8   If "Other," please indicate the currency here:                                                                                                                                                                                        225 non-null    str
 9   If your income needs additional context, please provide it here:                                                                                                                                                                      3053 non-null   str
 10  What country do you work in?                                                                                                                                                                                                          28224 non-null  str
 11  If you're in the U.S., what state do you work in?                                                                                                                                                                                     23148 non-null  str
 12  What city do you work in?                                                                                                                                                                                                             28141 non-null  str
 13  How many years of professional work experience do you have overall?                                                                                                                                                                   28226 non-null  str
 14  How many years of professional work experience do you have in your field?                                                                                                                                                             28226 non-null  str
 15  What is your highest level of education completed?                                                                                                                                                                                    27985 non-null  str
 16  What is your gender?                                                                                                                                                                                                                  28040 non-null  str
 17  What is your race? (Choose all that apply.)                                                                                                                                                                                           28029 non-null  str
dtypes: float64(1), str(17)
memory usage: 3.9 MB

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [23]:
# Rename ‘em.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race

#renamed the dataframe columns!
#alters the org dataframe, num of list items == num of col
df_salary.columns = ["timestamp", "age", "industry", "title", "title_context", "salary", "additional_compensation", "currency", "other_currency", "salary_context", "country", "state", "city", "total_yoe", "field_yoe", "highest_education_completed","gender", "race"]

In [24]:
df_salary #print the dataframe with the renamed col

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28221,6/2/2026 14:06:08,25-34,"Accounting, Banking & Finance",Accountant,NaN,53000,6000.0,GBP,NaN,NaN,UK,NaN,London,2 - 4 years,2 - 4 years,College degree,Other or prefer not to answer,Another option not listed here or prefer not t...
28222,6/22/2026 1:24:59,18-24,Education (Higher Education),student,NaN,0,NaN,Other,PKR,NaN,pakistan,NaN,faisalabad,1 year or less,1 year or less,College degree,Man,Another option not listed here or prefer not t...
28223,7/25/2026 5:10:49,18-24,Education (Primary/Secondary),English Teacher,NaN,31200,NaN,Other,MYR,NaN,Malaysia,NaN,Pahang,1 year or less,1 year or less,College degree,Woman,Asian or Asian American
28224,7/27/2026 11:44:14,35-44,Retail,purchasing coordinator,NaN,12000,0.0,USD,NaN,NaN,romania,NaN,bucharest,11 - 20 years,5-7 years,College degree,Man,White
28225,9/17/2026 20:18:08,25-34,Computing or Tech,Arbol,NaN,21,NaN,USD,NaN,NaN,Ecuador,Alabama,Texas,41 years or more,11 - 20 years,High School,Non-binary,Black or African American

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [25]:
# List the unique industries and a count of their instances.

#use value_counts
df_salary['industry'].value_counts()

industry
Computing or Tech                       4725
Education (Higher Education)            2481
Nonprofits                              2421
Health care                             1905
Government and Public Administration    1894
                                        ...
ABA                                        1
psychology                                 1
School                                     1
lifeguard                                  1
study                                      1
Name: count, Length: 1225, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new dataframe.

In [26]:
# Filtery filter. (Save it to a new variable, df_salary_tech.)

#only keep the rows in Computing/Tech?

#use .isin()
industry = ['Computing or Tech']

condition = df_salary.industry.isin(industry) #industry is the col name, create condition to retrieve rows that are Computing or Tech industry

Do a sanity check to make sure that the only values you kept are the one you are filtered for.

In [27]:
# Sanity Check 

df_salary[condition] #display the filtered data

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28180,10/30/2025 11:48:05,18-24,Computing or Tech,Business analyst,NaN,115000,12000.0,EUR,NaN,NaN,U.K.,NaN,london,2 - 4 years,1 year or less,Master's degree,Man,Black or African American
28184,12/9/2025 3:50:26,25-34,Computing or Tech,Data Analyst,NaN,72000,20.0,Other,ZMW,NaN,Zambia,NaN,Lusaka,1 year or less,1 year or less,Some college,Man,Black or African American
28188,1/8/2026 16:02:32,55-64,Computing or Tech,Senior Technical Writer,NaN,125000,5000.0,CAD,NaN,NaN,Canada,NaN,Toronto,31 - 40 years,21 - 30 years,College degree,Woman,White
28216,5/26/2026 20:05:52,25-34,Computing or Tech,Lead Messaging Operations Specialist,NaN,70000,4000.0,USD,NaN,NaN,USA,Maryland,Baltimore,11 - 20 years,8 - 10 years,College degree,Man,Black or African American
28225,9/17/2026 20:18:08,25-34,Computing or Tech,Arbol,NaN,21,NaN,USD,NaN,NaN,Ecuador,Alabama,Texas,41 years or more,11 - 20 years,High School,Non-binary,Black or African American

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [28]:
# Filtery filter for just the jobs that pay in USD!

#want values from currency col to be USD

curr_condition = df_salary['currency'] == 'USD' #create condition for USD 

df_salary[curr_condition] #display the filtered data

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
5,4/27/2021 11:02:46,25-34,Education (Higher Education),Scholarly Publishing Librarian,NaN,"62,000",NaN,USD,NaN,NaN,USA,New Hampshire,Hanover,8 - 10 years,2 - 4 years,Master's degree,Man,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28216,5/26/2026 20:05:52,25-34,Computing or Tech,Lead Messaging Operations Specialist,NaN,70000,4000.0,USD,NaN,NaN,USA,Maryland,Baltimore,11 - 20 years,8 - 10 years,College degree,Man,Black or African American
28219,6/1/2026 10:48:15,18-24,Data Analytics,Data Analyst,NaN,80000,5000.0,USD,NaN,NaN,United States,Michigan,East Lansing,1 year or less,2 - 4 years,Some college,Man,White
28220,6/1/2026 10:50:38,18-24,NaN,NaN,NaN,20,NaN,USD,NaN,NaN,United states,NaN,Detroit,2 - 4 years,1 year or less,NaN,NaN,NaN
28224,7/27/2026 11:44:14,35-44,Retail,purchasing coordinator,NaN,12000,0.0,USD,NaN,NaN,romania,NaN,bucharest,11 - 20 years,5-7 years,College degree,Man,White
28225,9/17/2026 20:18:08,25-34,Computing or Tech,Arbol,NaN,21,NaN,USD,NaN,NaN,Ecuador,Alabama,Texas,41 years or more,11 - 20 years,High School,Non-binary,Black or African American

What we really want know is how each U.S. city pays in tech. What value in `country` represents the United States of America?

In [29]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

#count each unique country, use value_counts()
df_salary['country'].value_counts() #For some reason United States shows up 2x

country
United States     9036
USA               7963
US                2620
Canada            1576
United States      669
                  ...
Liberia              1
1                    1
Nigeria + UK         1
Zambia               1
romania              1
Name: count, Length: 391, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [30]:
# Replace them all with 'US'.

#saved in a diff dataframe!
#use replace method, replcae multiple values at once, use dictionary
df_salary2 = df_salary.replace({'country':{'United States': 'US'}, 'country': {'USA': 'US'}}) #replace US variations with US

Have a look at the count of each unique country again now.

In [31]:
# Count again.

df_salary2['country'].value_counts()  #still shows multiple United States, U.S., other variations

country
US                10583
United States      9036
Canada             1576
United States       669
U.S.                586
                  ...
Liberia               1
1                     1
Nigeria + UK          1
Zambia                1
romania               1
Name: count, Length: 390, dtype: int64

Did you notice anything interesting?

In [32]:
# BONUS CREDIT: resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [33]:

# BONUS CREDIT: if you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [34]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

In [35]:
df_salary2.info() #salary values are of str datatype

<class 'pandas.DataFrame'>
RangeIndex: 28226 entries, 0 to 28225
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   timestamp                    28226 non-null  str
 1   age                          28226 non-null  str
 2   industry                     28140 non-null  str
 3   title                        28221 non-null  str
 4   title_context                7293 non-null   str
 5   salary                       28226 non-null  str
 6   additional_compensation      20850 non-null  float64
 7   currency                     28226 non-null  str
 8   other_currency               225 non-null    str
 9   salary_context               3053 non-null   str
 10  country                      28224 non-null  str
 11  state                        23148 non-null  str
 12  city                         28141 non-null  str
 13  total_yoe                    28226 non-null  str
 14  field_yoe                    28226 non-null  str
 15  highest_education_completed  27985 non-null  str
 16  gender                       28040 non-null  str
 17  race                         28029 non-null  str
dtypes: float64(1), str(17)
memory usage: 3.9 MB

Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed.

In [36]:
# Fix it.

df_salary2['salary'] = pd.to_numeric(df_salary2['salary'].str.replace(",", "")) #remove the commas in the num
df_salary2

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,55000,0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,54600,4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,34000,NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,62000,3000.0,USD,NaN,NaN,US,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,60000,7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28221,6/2/2026 14:06:08,25-34,"Accounting, Banking & Finance",Accountant,NaN,53000,6000.0,GBP,NaN,NaN,UK,NaN,London,2 - 4 years,2 - 4 years,College degree,Other or prefer not to answer,Another option not listed here or prefer not t...
28222,6/22/2026 1:24:59,18-24,Education (Higher Education),student,NaN,0,NaN,Other,PKR,NaN,pakistan,NaN,faisalabad,1 year or less,1 year or less,College degree,Man,Another option not listed here or prefer not t...
28223,7/25/2026 5:10:49,18-24,Education (Primary/Secondary),English Teacher,NaN,31200,NaN,Other,MYR,NaN,Malaysia,NaN,Pahang,1 year or less,1 year or less,College degree,Woman,Asian or Asian American
28224,7/27/2026 11:44:14,35-44,Retail,purchasing coordinator,NaN,12000,0.0,USD,NaN,NaN,romania,NaN,bucharest,11 - 20 years,5-7 years,College degree,Man,White
28225,9/17/2026 20:18:08,25-34,Computing or Tech,Arbol,NaN,21,NaN,USD,NaN,NaN,Ecuador,Alabama,Texas,41 years or more,11 - 20 years,High School,Non-binary,Black or African American

Let’s try that again.

In [37]:
# Try it again. Yeah!

gb2 = df_salary2.groupby('state') #group by the state, org df has states for US only
gb2['salary'].agg( ['min', 'mean', 'max'] ).sort_values(by='mean', ascending = False) #sort by mean ins DESC order

,min,mean,max
state,,,
"Alabama, South Carolina",5000000,5.000000e+06,5000000
"Utah, Wisconsin",2000000,2.000000e+06,2000000
"Michigan, Texas, Washington",340000,3.400000e+05,340000
"Indiana, Ohio",245000,2.450000e+05,245000
Alaska,27040,2.286546e+05,10000000
...,...,...,...
"Maryland, New York",14000,1.400000e+04,14000
"Delaware, Louisiana",40,4.000000e+01,40
"Alabama, Alaska, Arizona",15,1.500000e+01,15
"Colorado, Delaware, New Jersey, West Virginia, Wyoming",5,5.000000e+00,5
"Idaho, Indiana, Iowa, Kansas, Kentucky, Louisiana, Maryland, Massachusetts, Michigan, Minnesota, Mississippi",1,1.000000e+00,1

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [38]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

df_salary2['timestamp'] = pd.to_datetime(df_salary2['timestamp']) #convert timestamp col to datetime datatype

df_salary2

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,2021-04-27 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,55000,0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,2021-04-27 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,54600,4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,2021-04-27 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,34000,NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,2021-04-27 11:02:41,25-34,Nonprofits,Program Manager,NaN,62000,3000.0,USD,NaN,NaN,US,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,2021-04-27 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,60000,7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28221,2026-06-02 14:06:08,25-34,"Accounting, Banking & Finance",Accountant,NaN,53000,6000.0,GBP,NaN,NaN,UK,NaN,London,2 - 4 years,2 - 4 years,College degree,Other or prefer not to answer,Another option not listed here or prefer not t...
28222,2026-06-22 01:24:59,18-24,Education (Higher Education),student,NaN,0,NaN,Other,PKR,NaN,pakistan,NaN,faisalabad,1 year or less,1 year or less,College degree,Man,Another option not listed here or prefer not t...
28223,2026-07-25 05:10:49,18-24,Education (Primary/Secondary),English Teacher,NaN,31200,NaN,Other,MYR,NaN,Malaysia,NaN,Pahang,1 year or less,1 year or less,College degree,Woman,Asian or Asian American
28224,2026-07-27 11:44:14,35-44,Retail,purchasing coordinator,NaN,12000,0.0,USD,NaN,NaN,romania,NaN,bucharest,11 - 20 years,5-7 years,College degree,Man,White
28225,2026-09-17 20:18:08,25-34,Computing or Tech,Arbol,NaN,21,NaN,USD,NaN,NaN,Ecuador,Alabama,Texas,41 years or more,11 - 20 years,High School,Non-binary,Black or African American

In [39]:
df_salary2.info() #timestamp datatype now datetime instead of str, also see salary datatype is now int

<class 'pandas.DataFrame'>
RangeIndex: 28226 entries, 0 to 28225
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   timestamp                    28226 non-null  datetime64[us]
 1   age                          28226 non-null  str
 2   industry                     28140 non-null  str
 3   title                        28221 non-null  str
 4   title_context                7293 non-null   str
 5   salary                       28226 non-null  int64
 6   additional_compensation      20850 non-null  float64
 7   currency                     28226 non-null  str
 8   other_currency               225 non-null    str
 9   salary_context               3053 non-null   str
 10  country                      28224 non-null  str
 11  state                        23148 non-null  str
 12  city                         28141 non-null  str
 13  total_yoe                    28226 non-null  str
 14  field_yoe                    28226 non-null  str
 15  highest_education_completed  27985 non-null  str
 16  gender                       28040 non-null  str
 17  race                         28029 non-null  str
dtypes: datetime64[us](1), float64(1), int64(1), str(15)
memory usage: 3.9 MB

In [40]:
#create a NEW col to show the year only
df_salary2['year'] = df_salary2['timestamp'].dt.year #extract year only from datetime type

df_salary2

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race,year
0,2021-04-27 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,55000,0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White,2021
1,2021-04-27 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,54600,4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White,2021
2,2021-04-27 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,34000,NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White,2021
3,2021-04-27 11:02:41,25-34,Nonprofits,Program Manager,NaN,62000,3000.0,USD,NaN,NaN,US,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White,2021
4,2021-04-27 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,60000,7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28221,2026-06-02 14:06:08,25-34,"Accounting, Banking & Finance",Accountant,NaN,53000,6000.0,GBP,NaN,NaN,UK,NaN,London,2 - 4 years,2 - 4 years,College degree,Other or prefer not to answer,Another option not listed here or prefer not t...,2026
28222,2026-06-22 01:24:59,18-24,Education (Higher Education),student,NaN,0,NaN,Other,PKR,NaN,pakistan,NaN,faisalabad,1 year or less,1 year or less,College degree,Man,Another option not listed here or prefer not t...,2026
28223,2026-07-25 05:10:49,18-24,Education (Primary/Secondary),English Teacher,NaN,31200,NaN,Other,MYR,NaN,Malaysia,NaN,Pahang,1 year or less,1 year or less,College degree,Woman,Asian or Asian American,2026
28224,2026-07-27 11:44:14,35-44,Retail,purchasing coordinator,NaN,12000,0.0,USD,NaN,NaN,romania,NaN,bucharest,11 - 20 years,5-7 years,College degree,Man,White,2026
28225,2026-09-17 20:18:08,25-34,Computing or Tech,Arbol,NaN,21,NaN,USD,NaN,NaN,Ecuador,Alabama,Texas,41 years or more,11 - 20 years,High School,Non-binary,Black or African American,2026

In [41]:
df_salary2.info() #year is int datatype

<class 'pandas.DataFrame'>
RangeIndex: 28226 entries, 0 to 28225
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   timestamp                    28226 non-null  datetime64[us]
 1   age                          28226 non-null  str
 2   industry                     28140 non-null  str
 3   title                        28221 non-null  str
 4   title_context                7293 non-null   str
 5   salary                       28226 non-null  int64
 6   additional_compensation      20850 non-null  float64
 7   currency                     28226 non-null  str
 8   other_currency               225 non-null    str
 9   salary_context               3053 non-null   str
 10  country                      28224 non-null  str
 11  state                        23148 non-null  str
 12  city                         28141 non-null  str
 13  total_yoe                    28226 non-null  str
 14  field_yoe                    28226 non-null  str
 15  highest_education_completed  27985 non-null  str
 16  gender                       28040 non-null  str
 17  race                         28029 non-null  str
 18  year                         28226 non-null  int32
dtypes: datetime64[us](1), float64(1), int32(1), int64(1), str(15)
memory usage: 4.0 MB

In [42]:
#create 2 conditions 
year1 = df_salary2['year'] == 2021
year2 = df_salary2['year'] == 2022

#create a new dataframe to filter for 2021 and 2022
df_salary_year = df_salary2[year1 | year2].copy() #use or operator because want data from 2021 or 2022, can't be both years at once
df_salary_year

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race,year
0,2021-04-27 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,55000,0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White,2021
1,2021-04-27 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,54600,4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White,2021
2,2021-04-27 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,34000,NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White,2021
3,2021-04-27 11:02:41,25-34,Nonprofits,Program Manager,NaN,62000,3000.0,USD,NaN,NaN,US,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White,2021
4,2021-04-27 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,60000,7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27917,2022-12-17 08:10:07,25-34,"Marketing, Advertising & PR",Senior Strategist,Creative Marketing Strategist,78000,0.0,Other,SGD,NaN,Singapore,NaN,Singapore,5-7 years,2 - 4 years,College degree,Woman,NaN,2022
27918,2022-12-19 15:54:49,25-34,Computing or Tech,UX/UI Designer,NaN,54000,0.0,CAD,NaN,Very generous vacation policy,Canada,NaN,Toronto,2 - 4 years,1 year or less,College degree,Woman,Another option not listed here or prefer not t...,2022
27919,2022-12-22 15:46:39,35-44,Nonprofits,Director of Government Affairs,NaN,89000,1000.0,USD,NaN,NaN,United States,Missouri,St. Louis,11 - 20 years,11 - 20 years,Master's degree,Man,White,2022
27920,2022-12-22 17:43:19,25-34,Entertainment,Analyst,Analyst in A&R Admin Department at record label,60000,NaN,USD,NaN,NaN,United States,New York,NYC,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American,2022
27921,2022-12-29 07:54:18,55-64,Health care,Physical therapist assistant,Home health,62400,NaN,USD,NaN,NaN,Usa,Colorado,Denver,31 - 40 years,21 - 30 years,Some college,Woman,White,2022

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)